### ISSUE TITLE
Developement Report: Authentication

### ISSUE THREAD

**Issue by lucafynn01** [maya-gawinowski/car-rental#33]

**Comment by mgrabysz** [comment]
Link to the document
[https://docs.google.com/document/d/11l5XcHWCBa2jzNAQ4E-yO7iMl393ziZcZgHLSJDcL6k/edit?usp=sharing](https://docs.google.com/document/d/11l5XcHWCBa2jzNAQ4E-yO7iMl393ziZcZgHLSJDcL6k/edit?usp=sharing)
