### ISSUE TITLE
Developement Report: Screens

### ISSUE THREAD

**Issue by lucafynn01** [maya-gawinowski/car-rental#34]
Everbody should put a paragraph on their screen in the dev report

**Comment by mgrabysz** [comment]
Link to the document
[https://docs.google.com/document/d/11l5XcHWCBa2jzNAQ4E-yO7iMl393ziZcZgHLSJDcL6k/edit?usp=sharing](https://docs.google.com/document/d/11l5XcHWCBa2jzNAQ4E-yO7iMl393ziZcZgHLSJDcL6k/edit?usp=sharing)
